export const Types = {
  LOGIN: "LOGIN",
  UPDATE_USER: "UPDATE_USER",
};

export const TeamTypes = {
  ADD_TEAM: "ADD_TEAM",
  EDIT_TEAM_NAME: "EDIT_TEAM_NAME",
  UPDATE_TEAM: "UPDATE_TEAM",
  DELETE_TEAM: "DELETE_TEAM",
  ADD_POKEMON_TO_TEAM: "ADD_POKEMON_TO_TEAM",
};
